# Generated by Django 3.2.15 on 2022-10-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=None, upload_to='', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
