# Generated by Django 3.2.15 on 2022-10-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0002_alter_profile_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(choices=[('Vladivostok', 'Владивосток'), ('Artem', 'Артем'), ('Nakhodka', 'Находка')], default='Vladivostok', max_length=16),
        ),
    ]
