# Generated by Django 3.2.15 on 2022-10-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0003_profile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('Ж', 'Female')], default='Male', max_length=1),
        ),
    ]
